In [61]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [62]:
df_Mobile = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Android.xlsx')  
df_Mobile

,Name,Red,Green,Blue,Gray,Contrast,Energy,Homogeneity,Asm,Correlation,Dissimilarity,Group,pH
0,BAL21.png,4.90,4.04,3.97,4.29,29.05,0.85,0.87,0.73,0.90,1.40,1,4.86
1,BAL22.png,5.32,4.56,4.41,4.76,31.18,0.85,0.87,0.73,0.91,1.43,1,4.86
2,BAL23.png,5.65,4.84,4.69,5.06,38.00,0.84,0.86,0.71,0.90,1.66,1,4.86
3,BAL24.png,6.06,5.20,5.04,5.44,42.86,0.84,0.86,0.70,0.89,1.77,1,4.86
4,BAL25.png,6.05,5.20,5.05,5.43,41.67,0.84,0.86,0.71,0.90,1.68,1,4.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,CD26.png,9.66,8.99,9.35,9.24,65.77,0.76,0.79,0.58,0.91,2.64,4,5.43
116,CD27.png,9.60,8.83,9.11,9.09,60.54,0.73,0.76,0.53,0.90,2.70,4,5.43
117,CD28.png,9.59,8.94,9.26,9.17,63.89,0.73,0.76,0.53,0.90,2.75,4,5.43
118,CD29.png,10.01,9.35,9.66,9.58,74.65,0.72,0.76,0.52,0.89,3.00,4,5.43
119,CD30.png,8.60,8.02,8.29,8.22,56.27,0.75,0.79,0.57,0.90,2.45,4,5.43

In [63]:
# Train Mobile iphone
df= df_Mobile
d1= df.iloc[:, 0:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
d4 = df.iloc[:,11:12]
hi_df = pd.concat([d1,d2,d3,d4], axis=1)
hi_df

,Name,Red,Green,Gray,Energy,Homogeneity,Asm,Correlation,Group
0,BAL21.png,4.90,4.04,4.29,0.85,0.87,0.73,0.90,1
1,BAL22.png,5.32,4.56,4.76,0.85,0.87,0.73,0.91,1
2,BAL23.png,5.65,4.84,5.06,0.84,0.86,0.71,0.90,1
3,BAL24.png,6.06,5.20,5.44,0.84,0.86,0.70,0.89,1
4,BAL25.png,6.05,5.20,5.43,0.84,0.86,0.71,0.90,1
...,...,...,...,...,...,...,...,...,...
115,CD26.png,9.66,8.99,9.24,0.76,0.79,0.58,0.91,4
116,CD27.png,9.60,8.83,9.09,0.73,0.76,0.53,0.90,4
117,CD28.png,9.59,8.94,9.17,0.73,0.76,0.53,0.90,4
118,CD29.png,10.01,9.35,9.58,0.72,0.76,0.52,0.89,4
119,CD30.png,8.60,8.02,8.22,0.75,0.79,0.57,0.90,4

In [64]:
# Iphone feature (Mobile)
df_Mobile = hi_df
BAL_1 = df_Mobile.iloc[0:10,1:8] #BAL
BPL_1 = df_Mobile.iloc[10:20,1:8] #BPL
CM_2= df_Mobile.iloc[20:30,1:8] #CM
BAM_3 = df_Mobile.iloc[50:60,1:8]#BAM
BPM_3 = df_Mobile.iloc[60:70,1:8]#BPM
BAD_4 = df_Mobile.iloc[90:100,1:8]#BAD
PD_4 = df_Mobile.iloc[100:110,1:8]#PD
PM_2= df_Mobile.iloc[30:40,1:8]#PM
PD_4

       Red  Green   Gray  Energy  Homogeneity   Asm  Correlation
100   8.62   8.37   8.51    0.75         0.78  0.57         0.88
101  10.61  10.28  10.46    0.71         0.75  0.51         0.87
102   9.24   8.94   9.10    0.74         0.77  0.54         0.88
103   8.98   8.68   8.84    0.75         0.77  0.56         0.89
104  10.87  10.35  10.60    0.70         0.73  0.49         0.88
105  11.40  10.93  11.14    0.69         0.73  0.48         0.88
106  11.36  10.84  11.09    0.70         0.73  0.49         0.87
107   6.94   6.65   6.79    0.76         0.79  0.58         0.90
108   8.60   8.35   8.50    0.75         0.78  0.57         0.88
109   7.11   6.85   7.00    0.77         0.80  0.60         0.88

In [65]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values

In [66]:
df=df_Mobile
Target_BAL_1 = df.iloc[0:10,8:9]#BAL
Target_BPL_1 = df.iloc[10:20,8:9]#BPL
Target_CM_2= df.iloc[20:30,8:9]#CM
Target_BAM_3 = df.iloc[50:60,8:9]#BAM
Target_BPM_3 = df.iloc[60:70,8:9]#BPM
Target_BAD_4 = df.iloc[90:100,8:9]#BAD
Target_PD_4 = df.iloc[100:110,8:9]#PD
Target_PM_2= df.iloc[30:40,8:9]#PM

In [67]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values

In [68]:
# # 80% training and 20% test
# fea_train_G1, fea_test_G1, tar_train_G1, tar_test_G1 = train_test_split(feature_G1,G1_target, test_size=0.2, random_state=1)
# fea_train_G2, fea_test_G2, tar_train_G2, tar_test_G2 = train_test_split(feature_G2,G2_target, test_size=0.2, random_state=1)
# fea_train_G3, fea_test_G3, tar_train_G3, tar_test_G3 = train_test_split(feature_G3,G3_target, test_size=0.2, random_state=1)
# fea_train_G4, fea_test_G4, tar_train_G4, tar_test_G4 = train_test_split(feature_G4,G4_target, test_size=0.2, random_state=1)

In [69]:
main_feature_train = np.concatenate((feature_G1, feature_G2,feature_G3,feature_G4), axis=0)
main_target_train=np.concatenate((G1_target, G2_target,G3_target,G4_target), axis=0)
# main_feature_test = np.concatenate(( fea_test_G1,  fea_test_G2, fea_test_G3, fea_test_G4), axis=0)
# main_target_test=np.concatenate((tar_test_G1, tar_test_G2,tar_test_G3,tar_test_G4), axis=0)

In [70]:
dTree = DecisionTreeClassifier(max_depth =30,min_samples_leaf = 4, max_features = 7)
dTree.fit(main_feature_train,main_target_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=30, max_features=7, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [71]:
  
df_all =pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Mobile_v2.xlsx')   
df = df_all

In [72]:
# Train Mobile

d1= df.iloc[:, 0:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
d4 = df.iloc[:,11:12]
hi_df = pd.concat([d1,d2,d3,d4], axis=1)
hi_df

,Name,Red,Green,Gray,Energy,Homogeneity,Asm,Correlation,Group
0,BAL11.png,14.22,10.22,10.95,0.69,0.71,0.48,0.86,1
1,BAL12.png,12.11,8.68,9.31,0.72,0.74,0.52,0.85,1
2,BAL13.png,9.49,6.79,7.28,0.76,0.78,0.58,0.86,1
3,BAL14.png,10.70,7.60,8.18,0.74,0.76,0.54,0.85,1
4,BAL15.png,9.77,6.98,7.50,0.75,0.77,0.57,0.85,1
...,...,...,...,...,...,...,...,...,...
115,CD16.png,19.60,16.13,16.93,0.66,0.68,0.43,0.88,4
116,CD17.png,10.34,8.11,8.59,0.69,0.72,0.48,0.81,4
117,CD18.png,11.42,8.95,9.47,0.67,0.69,0.44,0.83,4
118,CD19.png,10.79,8.41,8.93,0.66,0.70,0.44,0.82,4
119,CD20.png,9.36,7.37,7.79,0.69,0.71,0.47,0.81,4

In [73]:
# Andriod feature (Mobile)
df_Mobile = hi_df
BAL_1 = df_Mobile.iloc[0:10,1:8] #BAL
BPL_1 = df_Mobile.iloc[10:20,1:8] #BPL
CM_2= df_Mobile.iloc[20:30,1:8] #CM
BAM_3 = df_Mobile.iloc[50:60,1:8]#BAM
BPM_3 = df_Mobile.iloc[60:70,1:8]#BPM
BAD_4 = df_Mobile.iloc[90:100,1:8]#BAD
PD_4 = df_Mobile.iloc[100:110,1:8]#PD
PM_2= df_Mobile.iloc[30:40,1:8]#PM
BAL_1

     Red  Green   Gray  Energy  Homogeneity   Asm  Correlation
0  14.22  10.22  10.95    0.69         0.71  0.48         0.86
1  12.11   8.68   9.31    0.72         0.74  0.52         0.85
2   9.49   6.79   7.28    0.76         0.78  0.58         0.86
3  10.70   7.60   8.18    0.74         0.76  0.54         0.85
4   9.77   6.98   7.50    0.75         0.77  0.57         0.85
5  11.41   8.44   8.98    0.71         0.73  0.50         0.84
6  10.52   7.81   8.30    0.73         0.75  0.53         0.86
7  12.29   9.11   9.70    0.71         0.73  0.50         0.86
8  11.78   8.64   9.23    0.70         0.72  0.49         0.85
9  11.43   8.41   8.97    0.71         0.73  0.50         0.85

In [74]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values
len(feature_G4)

20

In [75]:

Target_BAL_1 = df_Mobile.iloc[0:10,8:9] #BAL
Target_BPL_1 = df_Mobile.iloc[10:20,8:9] #BPL
Target_CM_2= df_Mobile.iloc[20:30,8:9] #CM
Target_BAM_3 = df_Mobile.iloc[50:60,8:9]#BAM
Target_BPM_3 = df_Mobile.iloc[60:70,8:9]#BPM
Target_BAD_4 = df_Mobile.iloc[90:100,8:9]#BAD
Target_PD_4 = df_Mobile.iloc[100:110,8:9]#PD
Target_PM_2= df_Mobile.iloc[30:40,8:9]#PM

In [76]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values
G4_target

array([[4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]], dtype=int64)

In [77]:

# main_feature_train = np.concatenate((fea_train_G1, fea_train_G2,fea_train_G3,fea_train_G4), axis=0)
# main_target_train=np.concatenate((tar_train_G1, tar_train_G2,tar_train_G3,tar_train_G4), axis=0)
main_feature_test = np.concatenate(( feature_G1,feature_G2,feature_G3,feature_G4), axis=0)
main_target_test=np.concatenate((G1_target,G2_target,G3_target,G4_target), axis=0)
main_target_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]], dtype=int64)

In [78]:
MOBILE_TRAIN_DSLR_TEST = dTree.predict(main_feature_test)
MOBILE_TRAIN_DSLR_TEST

array([2, 3, 4, 3, 3, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2, 2,
       4, 3, 2, 2, 2, 4, 4, 4, 4, 2, 2, 2, 2, 3, 4, 3, 3, 3, 3, 4, 4, 4,
       2, 3, 4, 3, 4, 4, 3, 2, 3, 4, 4, 3, 3, 3, 4, 4, 4, 3, 3, 4, 3, 4,
       4, 4, 4, 4, 3, 4, 4, 4, 2, 3, 3, 4, 3, 3], dtype=int64)

In [79]:

print("\nDesicion Tree")

print("\nEvaluation of DTree Model : \n", classification_report(main_target_test, MOBILE_TRAIN_DSLR_TEST))

Desicion Tree

Evaluation of DTree Model :
               precision    recall  f1-score   support

           1       0.00      0.00      0.00        20
           2       0.45      0.45      0.45        20
           3       0.26      0.40      0.31        20
           4       0.38      0.55      0.45        20

    accuracy                           0.35        80
   macro avg       0.27      0.35      0.30        80
weighted avg       0.27      0.35      0.30        80

c:\users\u5988116\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))