In [1]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
df_Mobile = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Mobile_v2.xlsx')  
df_Mobile

,Name,Red,Green,Blue,Gray,Contrast,Energy,Homogeneity,Asm,Correlation,Dissimilarity,Group,pH
0,BAL11.png,14.22,10.22,6.14,10.95,98.80,0.69,0.71,0.48,0.86,4.32,1,4.86
1,BAL12.png,12.11,8.68,5.24,9.31,91.88,0.72,0.74,0.52,0.85,3.92,1,4.86
2,BAL13.png,9.49,6.79,4.06,7.28,60.24,0.76,0.78,0.58,0.86,3.02,1,4.86
3,BAL14.png,10.70,7.60,4.55,8.18,75.34,0.74,0.76,0.54,0.85,3.44,1,4.86
4,BAL15.png,9.77,6.98,4.23,7.50,67.35,0.75,0.77,0.57,0.85,3.09,1,4.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,CD16.png,19.60,16.13,14.09,16.93,187.53,0.66,0.68,0.43,0.88,5.94,4,5.43
116,CD17.png,10.34,8.11,6.52,8.59,95.70,0.69,0.72,0.48,0.81,4.10,4,5.43
117,CD18.png,11.42,8.95,7.02,9.47,93.11,0.67,0.69,0.44,0.83,4.32,4,5.43
118,CD19.png,10.79,8.41,6.69,8.93,87.49,0.66,0.70,0.44,0.82,4.10,4,5.43
119,CD20.png,9.36,7.37,5.84,7.79,76.09,0.69,0.71,0.47,0.81,3.77,4,5.43

In [2]:
# Train Mobile
df= df_Mobile
d1= df.iloc[:, 1:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
d4 = df.iloc[:,11:12]
hi_df = pd.concat([d1,d2,d3,d4], axis=1)
hi_df

       Red  Green   Gray  Energy  Homogeneity   Asm  Correlation  Group
0    14.22  10.22  10.95    0.69         0.71  0.48         0.86      1
1    12.11   8.68   9.31    0.72         0.74  0.52         0.85      1
2     9.49   6.79   7.28    0.76         0.78  0.58         0.86      1
3    10.70   7.60   8.18    0.74         0.76  0.54         0.85      1
4     9.77   6.98   7.50    0.75         0.77  0.57         0.85      1
..     ...    ...    ...     ...          ...   ...          ...    ...
115  19.60  16.13  16.93    0.66         0.68  0.43         0.88      4
116  10.34   8.11   8.59    0.69         0.72  0.48         0.81      4
117  11.42   8.95   9.47    0.67         0.69  0.44         0.83      4
118  10.79   8.41   8.93    0.66         0.70  0.44         0.82      4
119   9.36   7.37   7.79    0.69         0.71  0.47         0.81      4

[120 rows x 8 columns]

In [3]:
# (Mobile)
df_Mobile= hi_df
BAL_1 = df_Mobile.iloc[0:10,0:7] #BAL
BPL_1 = df_Mobile.iloc[10:20,0:7] #BPL
CM_2= df_Mobile.iloc[20:30,0:7] #CM
BAM_3 = df_Mobile.iloc[50:60,0:7]#BAM
BPM_3 = df_Mobile.iloc[60:70,0:7]#BPM
BAD_4 = df_Mobile.iloc[90:100,0:7]#BAD
PD_4 = df_Mobile.iloc[100:110,0:7]#PD
PM_2= df_Mobile.iloc[30:40,0:7]#PM
BAL_1

     Red  Green   Gray  Energy  Homogeneity   Asm  Correlation
0  14.22  10.22  10.95    0.69         0.71  0.48         0.86
1  12.11   8.68   9.31    0.72         0.74  0.52         0.85
2   9.49   6.79   7.28    0.76         0.78  0.58         0.86
3  10.70   7.60   8.18    0.74         0.76  0.54         0.85
4   9.77   6.98   7.50    0.75         0.77  0.57         0.85
5  11.41   8.44   8.98    0.71         0.73  0.50         0.84
6  10.52   7.81   8.30    0.73         0.75  0.53         0.86
7  12.29   9.11   9.70    0.71         0.73  0.50         0.86
8  11.78   8.64   9.23    0.70         0.72  0.49         0.85
9  11.43   8.41   8.97    0.71         0.73  0.50         0.85

In [4]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values

In [5]:
df = df_Mobile
Target_BAL_1 = df.iloc[0:10,7:8]#BAL
Target_BPL_1 = df.iloc[10:20,7:8]#BPL
Target_CM_2= df.iloc[20:30,7:8]#CM
Target_BAM_3 = df.iloc[50:60,7:8]#BAM
Target_BPM_3 = df.iloc[60:70,7:8]#BPM
Target_BAD_4 = df.iloc[90:100,7:8]#BAD
Target_PD_4 = df.iloc[100:110,7:8]#PD
Target_PM_2= df.iloc[30:40,7:8]#PM

In [6]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values

In [7]:
# # 80% training and 20% test
# fea_train_G1, fea_test_G1, tar_train_G1, tar_test_G1 = train_test_split(feature_G1,G1_target, test_size=0.2, random_state=1)
# fea_train_G2, fea_test_G2, tar_train_G2, tar_test_G2 = train_test_split(feature_G2,G2_target, test_size=0.2, random_state=1)
# fea_train_G3, fea_test_G3, tar_train_G3, tar_test_G3 = train_test_split(feature_G3,G3_target, test_size=0.2, random_state=1)
# fea_train_G4, fea_test_G4, tar_train_G4, tar_test_G4 = train_test_split(feature_G4,G4_target, test_size=0.2, random_state=1)

In [8]:
main_feature_train = np.concatenate((feature_G1, feature_G2,feature_G3,feature_G4), axis=0)
main_target_train=np.concatenate((G1_target, G2_target,G3_target,G4_target), axis=0)
# main_feature_test = np.concatenate(( fea_test_G1,  fea_test_G2, fea_test_G3, fea_test_G4), axis=0)
# main_target_test=np.concatenate((tar_test_G1, tar_test_G2,tar_test_G3,tar_test_G4), axis=0)

In [9]:
dTree = DecisionTreeClassifier(max_depth = 8, min_samples_leaf = 4, max_features = 7)
dTree.fit(main_feature_train,main_target_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=8, max_features=7, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [10]:
df_Mobile = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Mobile_v2.xlsx')  
df_all =pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_DSLR_20.xlsx')   
df = df_all

In [11]:

d1= df.iloc[:, 1:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
hi_df = pd.concat([d1,d2,d3], axis=1) #high corr feature
hi_df

      Red  Green   Gray  Energy  Homogeneity   Asm  Correlation
0   19.17  13.49  14.62    0.73         0.77  0.53         0.96
1   17.23  12.19  13.16    0.73         0.77  0.53         0.95
2   17.39  12.53  13.47    0.73         0.77  0.53         0.95
3   16.62  11.73  12.69    0.75         0.78  0.56         0.95
4   14.97  10.67  11.50    0.74         0.79  0.55         0.94
..    ...    ...    ...     ...          ...   ...          ...
75  15.56  11.16  12.06    0.67         0.69  0.45         0.87
76  13.78   9.55  10.43    0.68         0.70  0.46         0.86
77  14.76  10.34  11.26    0.65         0.68  0.42         0.86
78  13.60   9.54  10.38    0.65         0.68  0.42         0.86
79  13.48   9.46  10.29    0.68         0.71  0.46         0.87

[80 rows x 7 columns]

In [12]:
BAL_1 = hi_df.iloc[0:10,0:7] #BAL
BPL_1 = hi_df.iloc[10:20,0:7] #BPL
CM_2= hi_df.iloc[20:30,0:7] #CM
BAM_3 = hi_df.iloc[30:40,0:7]#BAM
BPM_3 = hi_df.iloc[40:50,0:7]#BPM
BAD_4 = hi_df.iloc[50:60,0:7]#BAD
PD_4 = hi_df.iloc[60:70,0:7]#PD
PM_2= hi_df.iloc[70:80,0:7]#PM
BAL_1

     Red  Green   Gray  Energy  Homogeneity   Asm  Correlation
0  19.17  13.49  14.62    0.73         0.77  0.53         0.96
1  17.23  12.19  13.16    0.73         0.77  0.53         0.95
2  17.39  12.53  13.47    0.73         0.77  0.53         0.95
3  16.62  11.73  12.69    0.75         0.78  0.56         0.95
4  14.97  10.67  11.50    0.74         0.79  0.55         0.94
5  14.46  10.35  11.14    0.75         0.79  0.56         0.95
6  15.57  11.12  11.98    0.74         0.78  0.54         0.95
7  16.79  12.02  12.95    0.73         0.78  0.54         0.96
8  17.91  12.76  13.78    0.73         0.77  0.53         0.95
9  16.14  11.60  12.49    0.74         0.78  0.55         0.95

In [13]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values

In [14]:
Target_BAL_1 = df.iloc[0:10,11:12]#BAL
Target_BPL_1 = df.iloc[10:20,11:12]#BPL
Target_CM_2= df.iloc[20:30,11:12]#CM
Target_BAM_3 = df.iloc[30:40,11:12]#BAM
Target_BPM_3 = df.iloc[40:50,11:12]#BPM
Target_BAD_4 = df.iloc[50:60,11:12]#BAD
Target_PD_4 = df.iloc[60:70,11:12]#PD
Target_PM_2= df.iloc[70:80,11:12]#PM

In [15]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values

In [16]:
# # 80% training and 20% test
# fea_train_G1, fea_test_G1, tar_train_G1, tar_test_G1 = train_test_split(feature_G1,G1_target, test_size=0.2, random_state=1)
# fea_train_G2, fea_test_G2, tar_train_G2, tar_test_G2 = train_test_split(feature_G2,G2_target, test_size=0.2, random_state=1)
# fea_train_G3, fea_test_G3, tar_train_G3, tar_test_G3 = train_test_split(feature_G3,G3_target, test_size=0.2, random_state=1)
# fea_train_G4, fea_test_G4, tar_train_G4, tar_test_G4 = train_test_split(feature_G4,G4_target, test_size=0.2, random_state=1)

In [17]:

# main_feature_train = np.concatenate((fea_train_G1, fea_train_G2,fea_train_G3,fea_train_G4), axis=0)
# main_target_train=np.concatenate((tar_train_G1, tar_train_G2,tar_train_G3,tar_train_G4), axis=0)
main_feature_test = np.concatenate(( feature_G1,feature_G2,feature_G3,feature_G4), axis=0)
main_target_test=np.concatenate((G1_target,G2_target,G3_target,G4_target), axis=0)
len(main_target_test)

80

In [18]:
Mobile_test_model = dTree.predict(main_feature_test)
Mobile_test_model

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2], dtype=int64)

In [19]:

print("\nDesicion Tree")

print("\nEvaluation of DTree Model : \n", classification_report(main_target_test,Mobile_test_model ))

Desicion Tree

Evaluation of DTree Model :
               precision    recall  f1-score   support

           1       0.28      1.00      0.43        20
           2       0.12      0.05      0.07        20
           3       0.00      0.00      0.00        20
           4       0.00      0.00      0.00        20

    accuracy                           0.26        80
   macro avg       0.10      0.26      0.13        80
weighted avg       0.10      0.26      0.13        80

c:\users\u5988116\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))