In [23]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
df_Mobile = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Mobile_v2.xlsx')  
df_Mobile

,Name,Red,Green,Blue,Gray,Contrast,Energy,Homogeneity,Asm,Correlation,Dissimilarity,Group,pH
0,BAL11.png,14.22,10.22,6.14,10.95,98.80,0.69,0.71,0.48,0.86,4.32,1,4.86
1,BAL12.png,12.11,8.68,5.24,9.31,91.88,0.72,0.74,0.52,0.85,3.92,1,4.86
2,BAL13.png,9.49,6.79,4.06,7.28,60.24,0.76,0.78,0.58,0.86,3.02,1,4.86
3,BAL14.png,10.70,7.60,4.55,8.18,75.34,0.74,0.76,0.54,0.85,3.44,1,4.86
4,BAL15.png,9.77,6.98,4.23,7.50,67.35,0.75,0.77,0.57,0.85,3.09,1,4.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,CD16.png,19.60,16.13,14.09,16.93,187.53,0.66,0.68,0.43,0.88,5.94,4,5.43
116,CD17.png,10.34,8.11,6.52,8.59,95.70,0.69,0.72,0.48,0.81,4.10,4,5.43
117,CD18.png,11.42,8.95,7.02,9.47,93.11,0.67,0.69,0.44,0.83,4.32,4,5.43
118,CD19.png,10.79,8.41,6.69,8.93,87.49,0.66,0.70,0.44,0.82,4.10,4,5.43
119,CD20.png,9.36,7.37,5.84,7.79,76.09,0.69,0.71,0.47,0.81,3.77,4,5.43

In [24]:
# Train Mobile
df= df_Mobile
d1= df.iloc[:, 1:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
d4 = df.iloc[:,11:12]
hi_df = pd.concat([d1,d2,d3,d4], axis=1)
hi_df

       Red  Green   Gray  Energy  Homogeneity   Asm  Correlation  Group
0    14.22  10.22  10.95    0.69         0.71  0.48         0.86      1
1    12.11   8.68   9.31    0.72         0.74  0.52         0.85      1
2     9.49   6.79   7.28    0.76         0.78  0.58         0.86      1
3    10.70   7.60   8.18    0.74         0.76  0.54         0.85      1
4     9.77   6.98   7.50    0.75         0.77  0.57         0.85      1
..     ...    ...    ...     ...          ...   ...          ...    ...
115  19.60  16.13  16.93    0.66         0.68  0.43         0.88      4
116  10.34   8.11   8.59    0.69         0.72  0.48         0.81      4
117  11.42   8.95   9.47    0.67         0.69  0.44         0.83      4
118  10.79   8.41   8.93    0.66         0.70  0.44         0.82      4
119   9.36   7.37   7.79    0.69         0.71  0.47         0.81      4

[120 rows x 8 columns]

In [25]:
# (Mobile)
df_Mobile= hi_df
BAL_1 = df_Mobile.iloc[0:10,0:7] #BAL
BPL_1 = df_Mobile.iloc[10:20,0:7] #BPL
CM_2= df_Mobile.iloc[20:30,0:7] #CM
BAM_3 = df_Mobile.iloc[50:60,0:7]#BAM
BPM_3 = df_Mobile.iloc[60:70,0:7]#BPM
BAD_4 = df_Mobile.iloc[90:100,0:7]#BAD
PD_4 = df_Mobile.iloc[100:110,0:7]#PD
PM_2= df_Mobile.iloc[30:40,0:7]#PM
BAL_1

     Red  Green   Gray  Energy  Homogeneity   Asm  Correlation
0  14.22  10.22  10.95    0.69         0.71  0.48         0.86
1  12.11   8.68   9.31    0.72         0.74  0.52         0.85
2   9.49   6.79   7.28    0.76         0.78  0.58         0.86
3  10.70   7.60   8.18    0.74         0.76  0.54         0.85
4   9.77   6.98   7.50    0.75         0.77  0.57         0.85
5  11.41   8.44   8.98    0.71         0.73  0.50         0.84
6  10.52   7.81   8.30    0.73         0.75  0.53         0.86
7  12.29   9.11   9.70    0.71         0.73  0.50         0.86
8  11.78   8.64   9.23    0.70         0.72  0.49         0.85
9  11.43   8.41   8.97    0.71         0.73  0.50         0.85

In [26]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4

In [27]:
df = df_Mobile
Target_BAL_1 = df.iloc[0:10,7:8]#BAL
Target_BPL_1 = df.iloc[10:20,7:8]#BPL
Target_CM_2= df.iloc[20:30,7:8]#CM
Target_BAM_3 = df.iloc[50:60,7:8]#BAM
Target_BPM_3 = df.iloc[60:70,7:8]#BPM
Target_BAD_4 = df.iloc[90:100,7:8]#BAD
Target_PD_4 = df.iloc[100:110,7:8]#PD
Target_PM_2= df.iloc[30:40,7:8]#PM

In [28]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1])
G2_target = pd.concat([Target_CM_2,Target_PM_2])
G3_target = pd.concat([Target_BAM_3,Target_BPM_3])
G4_target = pd.concat([Target_BAD_4,Target_PD_4])

In [29]:
# 80% training and 20% test (Iphone)
fea_train_G1, fea_test_G1, tar_train_G1, tar_test_G1 = train_test_split(feature_G1, G1_target,test_size=0.2, random_state=1)
fea_train_G2, fea_test_G2, tar_train_G2, tar_test_G2 = train_test_split(feature_G2, G2_target,test_size=0.2, random_state=1)
fea_train_G3, fea_test_G3, tar_train_G3, tar_test_G3 = train_test_split(feature_G3, G3_target, test_size=0.2, random_state=1)
fea_train_G4, fea_test_G4, tar_train_G4, tar_test_G4 = train_test_split(feature_G4, G4_target,test_size=0.2, random_state=1)

In [30]:
# prepare for samsung
df_Android = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Android.xlsx')  

df_Android

,Name,Red,Green,Blue,Gray,Contrast,Energy,Homogeneity,Asm,Correlation,Dissimilarity,Group,pH
0,BAL21.png,4.90,4.04,3.97,4.29,29.05,0.85,0.87,0.73,0.90,1.40,1,4.86
1,BAL22.png,5.32,4.56,4.41,4.76,31.18,0.85,0.87,0.73,0.91,1.43,1,4.86
2,BAL23.png,5.65,4.84,4.69,5.06,38.00,0.84,0.86,0.71,0.90,1.66,1,4.86
3,BAL24.png,6.06,5.20,5.04,5.44,42.86,0.84,0.86,0.70,0.89,1.77,1,4.86
4,BAL25.png,6.05,5.20,5.05,5.43,41.67,0.84,0.86,0.71,0.90,1.68,1,4.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,CD26.png,9.66,8.99,9.35,9.24,65.77,0.76,0.79,0.58,0.91,2.64,4,5.43
116,CD27.png,9.60,8.83,9.11,9.09,60.54,0.73,0.76,0.53,0.90,2.70,4,5.43
117,CD28.png,9.59,8.94,9.26,9.17,63.89,0.73,0.76,0.53,0.90,2.75,4,5.43
118,CD29.png,10.01,9.35,9.66,9.58,74.65,0.72,0.76,0.52,0.89,3.00,4,5.43
119,CD30.png,8.60,8.02,8.29,8.22,56.27,0.75,0.79,0.57,0.90,2.45,4,5.43

In [31]:
# Train Mobile
df = df_Android

d1= df.iloc[:, 1:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
d4 = df.iloc[:,11:12]
hi_df = pd.concat([d1,d2,d3,d4], axis=1)
hi_df

       Red  Green  Gray  Energy  Homogeneity   Asm  Correlation  Group
0     4.90   4.04  4.29    0.85         0.87  0.73         0.90      1
1     5.32   4.56  4.76    0.85         0.87  0.73         0.91      1
2     5.65   4.84  5.06    0.84         0.86  0.71         0.90      1
3     6.06   5.20  5.44    0.84         0.86  0.70         0.89      1
4     6.05   5.20  5.43    0.84         0.86  0.71         0.90      1
..     ...    ...   ...     ...          ...   ...          ...    ...
115   9.66   8.99  9.24    0.76         0.79  0.58         0.91      4
116   9.60   8.83  9.09    0.73         0.76  0.53         0.90      4
117   9.59   8.94  9.17    0.73         0.76  0.53         0.90      4
118  10.01   9.35  9.58    0.72         0.76  0.52         0.89      4
119   8.60   8.02  8.22    0.75         0.79  0.57         0.90      4

[120 rows x 8 columns]

In [32]:
df_Mobile2 = hi_df
BAL_1_AN = df_Mobile2.iloc[0:10,0:7] #BAL
BPL_1_AN = df_Mobile2.iloc[10:20,0:7] #BPL
CM_2_AN= df_Mobile2.iloc[20:30,0:7] #CM
BAM_3_AN = df_Mobile2.iloc[50:60,0:7]#BAM
BPM_3_AN = df_Mobile2.iloc[60:70,0:7]#BPM
BAD_4_AN = df_Mobile2.iloc[90:100,0:7]#BAD
PD_4_AN = df_Mobile2.iloc[100:110,0:7]#PD
PM_2_AN= df_Mobile2.iloc[30:40,0:7]#PM
BAL_1_AN

    Red  Green  Gray  Energy  Homogeneity   Asm  Correlation
0  4.90   4.04  4.29    0.85         0.87  0.73         0.90
1  5.32   4.56  4.76    0.85         0.87  0.73         0.91
2  5.65   4.84  5.06    0.84         0.86  0.71         0.90
3  6.06   5.20  5.44    0.84         0.86  0.70         0.89
4  6.05   5.20  5.43    0.84         0.86  0.71         0.90
5  6.30   5.37  5.64    0.84         0.86  0.71         0.89
6  8.35   7.31  7.59    0.80         0.82  0.64         0.90
7  7.02   5.97  6.26    0.82         0.84  0.68         0.89
8  7.70   6.60  6.91    0.81         0.83  0.66         0.89
9  7.64   6.54  6.86    0.81         0.83  0.65         0.89

In [33]:
df = hi_df
Target_BAL_1_AN = df.iloc[0:10,7:8]#BAL
Target_BPL_1_AN = df.iloc[10:20,7:8]#BPL
Target_CM_2_AN= df.iloc[20:30,7:8]#CM
Target_BAM_3_AN = df.iloc[50:60,7:8]#BAM
Target_BPM_3_AN = df.iloc[60:70,7:8]#BPM
Target_BAD_4_AN = df.iloc[90:100,7:8]#BAD
Target_PD_4_AN = df.iloc[100:110,7:8]#PD
Target_PM_2_AN= df.iloc[30:40,7:8]#PM

In [34]:
G1_target_AN = pd.concat([Target_BAL_1_AN, Target_BPL_1_AN])
G2_target_AN = pd.concat([Target_CM_2_AN,Target_PM_2_AN])
G3_target_AN = pd.concat([Target_BAM_3_AN,Target_BPM_3_AN])
G4_target_AN = pd.concat([Target_BAD_4_AN,Target_PD_4_AN])

In [35]:
# 80% training and 20% test (Android)
fea_train_G1_AN, fea_test_G1_AN, tar_train_G1_AN, tar_test_G1_AN = train_test_split(feature_G1_AN, G1_target_AN,test_size=0.2, random_state=1)
fea_train_G2_AN, fea_test_G2_AN, tar_train_G2_AN, tar_test_G2_AN = train_test_split(feature_G2_AN, G2_target_AN,test_size=0.2, random_state=1)
fea_train_G3_AN, fea_test_G3_AN, tar_train_G3_AN, tar_test_G3_AN = train_test_split(feature_G3_AN, G3_target_AN, test_size=0.2, random_state=1)
fea_train_G4_AN, fea_test_G4_AN, tar_train_G4_AN, tar_test_G4_AN = train_test_split(feature_G4_AN, G4_target_AN,test_size=0.2, random_state=1)
tar_test_G1_AN

    Group
3       1
16      1
6       1
10      1

In [36]:
main_feature_train = np.concatenate((  fea_train_G1,fea_train_G1_AN,fea_train_G2,fea_train_G2_AN,fea_train_G3,fea_train_G3_AN,fea_train_G4,fea_train_G4_AN), axis=0)
main_target_train=np.concatenate(( tar_train_G1,tar_train_G1_AN,tar_train_G2,tar_train_G2_AN,tar_train_G3,tar_train_G3_AN,tar_train_G4,tar_train_G4_AN), axis=0)
main_feature_test = np.concatenate(( fea_test_G1,fea_test_G1_AN, fea_test_G2,fea_test_G2_AN, fea_test_G3,fea_test_G3_AN, fea_test_G4,fea_test_G4_AN), axis=0)
main_target_test=np.concatenate(( tar_test_G1,tar_test_G1_AN,tar_test_G2,tar_test_G2_AN,tar_test_G3,tar_test_G3_AN,tar_test_G4,tar_test_G4_AN), axis=0)

In [53]:
dTree = DecisionTreeClassifier(max_depth = 30, min_samples_leaf = 4, max_features = 7)
dTree.fit(main_feature_train,main_target_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=30, max_features=7, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [54]:
Mobile_test_model = dTree.predict(main_feature_test)
Mobile_test_model

array([4, 1, 4, 4, 1, 1, 1, 1, 2, 1, 4, 4, 4, 2, 4, 1, 4, 3, 3, 4, 3, 1,
       3, 4, 3, 4, 3, 4, 4, 4, 2, 4], dtype=int64)

In [55]:

print("\nDesicion Tree")

print("\nEvaluation of DTree Model : \n", classification_report(main_target_test,Mobile_test_model ))

Desicion Tree

Evaluation of DTree Model :
               precision    recall  f1-score   support

           1       0.62      0.62      0.62         8
           2       0.67      0.25      0.36         8
           3       0.67      0.50      0.57         8
           4       0.33      0.62      0.43         8

    accuracy                           0.50        32
   macro avg       0.57      0.50      0.50        32
weighted avg       0.57      0.50      0.50        32

In [62]:
from sklearn.metrics import classification_report 
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes= 2048, random_state=1000)
MLP.fit(main_feature_train,main_target_train)

c:\users\u5988116\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\u5988116\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=2048, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1000, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [63]:
ModelDT = MLP.predict(main_feature_test)
ModelDT

array([1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 4, 2, 4, 2, 2, 3, 3, 1, 3, 3,
       3, 4, 3, 3, 4, 3, 4, 4, 4, 4], dtype=int64)

In [64]:
print("\nNeural network")

print("\nEvaluation of DTree Model : \n", classification_report(main_target_test, ModelDT))

Neural network

Evaluation of DTree Model :
               precision    recall  f1-score   support

           1       0.64      0.88      0.74         8
           2       0.60      0.38      0.46         8
           3       0.62      0.62      0.62         8
           4       0.62      0.62      0.62         8

    accuracy                           0.62        32
   macro avg       0.62      0.62      0.61        32
weighted avg       0.62      0.62      0.61        32